services:
  - type: web
    name: trafikking-x-backend
    runtime: docker
    rootDir: trafikking-x-backend
    dockerfilePath: ./Dockerfile
    plan: free

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: JWT_SECRET
        sync: false